[package]
name = "ruma-common"
version = "0.1.3"
authors = ["Jonas Platte <jplatte@posteo.de>"]
description = "Common types for other ruma crates."
homepage = "https://github.com/ruma/ruma-common"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
edition = "2018"

[dependencies]
matches = "0.1.8"
ruma-serde = { version = "0.2.2", path = "../ruma-serde" }
serde = { version = "1.0.111", features = ["derive"] }
serde_json = { version = "1.0.53", features = ["raw_value"] }
strum = { version = "0.18.0", features = ["derive"] }
