language: "rust"
cache: "cargo"
before_script:
  - "rustup component add rustfmt"
  - "rustup component add clippy"
  - "cargo install --force cargo-audit"
  - "cargo generate-lockfile"
script:
  - "cargo audit"
  - "cargo fmt --all -- --check"
  - "cargo clippy --all-targets --all-features -- -D warnings"
  - "cargo build --verbose"
  - "cargo test --verbose"
if: "type != push OR (tag IS blank AND branch = master)"
notifications:
  email: false
  irc:
    channels:
      - secure: "Z4Bo39O8Zl/xGJ3A3P08sKO12YMpQOMwwWou9oZxYGnaVQM/1hlpgMrPKtif4v+681SGMuUoA97P0Tr93oSSGqyJalN2dcft9vOiFa1Izo5nVuJ1+8trTRxV+3oE7X30ixh/jWg4oXPrfLbKMv1Bp7htjffNQQcsh2RrPjmhK3PtuqTLeY0OFm6uKIa/4fmz2d2PV+V2GRhFvI4b4HRLAQDRbFrD3MUReSqqWCpAdnyswKOVZMcCNZHuBpPdZK+lARopZsruN5LcDi787CRel79K+Cmqif1jyGgwQusjrP2c4Bjdi6SGCy2V5TNMYgYrp1ox/gLaHNC3A1aHZYmbHXI908aANbt860Y/1N0ax3CbEkUFFSfiEjnw816BTJ61/kccMEUN6nYpbj/hkyNApCXYlp65+FAx2NaQCV6obvWh7ymF3Mp8v1OvidEKbhvDqhuGQ62ZZGWVUpzKAe0QRQ2NFFPm53nOrcVHdR4ZMKdGrsgAgpvX1d92JmChqlZbEjbCZRs+KHj1Bkfwkousu9+VNLQatc+VwiqXXHnOi9jCVecqmtLnioP3UvYBEQKsh2gv5GhUwluqrSMNfy3H51Zg/lLMHQHUZw5XZgb7nenCBcrmSl4h75+z1lUdkE5UQn3WcjVOVsbwS/qpHHJ+CRKnpcSBqIE1pb0BFdI5/MU="
    use_notice: true
