language: "rust"
cache: "cargo"
rust:
  - 1.40.0
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo generate-lockfile
script:
  - cargo fmt -- --check
  - |
      if [ "$TRAVIS_RUST_VERSION" != "1.39.0" ]; then
        cargo clippy --all-targets --all-features -- -D warnings
      fi
  - cargo build --verbose
  - cargo test --verbose
if: "type != push OR (tag IS blank AND branch = master)"
