[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable types for the events in the Matrix specification."
documentation = "https://ruma.github.io/ruma-events/ruma_events/"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.1.0"

[dependencies]
ruma-identifiers = "0.5.0"
ruma-signatures = "0.1.0"
serde = "0.8.19"
serde_derive = "0.8.19"
serde_json = "0.8.4"
