[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories ["api-bindings", "web-programming"]
description = "An abstraction for Matrix API endpoints."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.8.0"
edition = "2018"

[dependencies]
futures = "0.1.27"
http = "0.1.17"
hyper = "0.12.29"
serde_json = "1.0.39"
serde_urlencoded = "0.5.5"
ruma-identifiers = "0.13.0"

[dev-dependencies]
url = "1.7.2"

[dev-dependencies.serde]
version = "1.0.92"
features = ["derive"]
