[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "ruma-api-macros"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
synom = "0.11.3"

[dependencies.ruma-api]
git = "https://github.com/ruma/ruma-api"
rev = "211cf5e3531cd1862136129d5f73caaac7b4eb43"

[dependencies.syn]
features = ["full"]
version = "0.11.11"

[dev-dependencies]
futures = "0.1.14"
hyper = "0.11"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_urlencoded = "0.5.1"

[lib]
doctest = false
proc-macro = true
