[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Resource identifiers for Matrix."
documentation = "https://ruma.github.io/ruma-identifiers/ruma_identifiers/"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.6.0"

[dependencies]
lazy_static = "0.2.2"
rand = "0.3.15"
regex = "0.2.1"
serde = "0.9.1"
url = "1.4.0"

[dependencies.diesel]
optional = true
version = "0.9.0"

[dev-dependencies]
serde_json = "0.9.1"
