[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable types for the events in the Matrix specification."
documentation = "https://docs.rs/ruma-events"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.7.0"

[dependencies]
ruma-identifiers = "0.11"
ruma-signatures = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
