[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Resource identifiers for Matrix."
documentation = "https://ruma.github.io/ruma-identifiers/ruma_identifiers/"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.3.0"

[dependencies]
lazy_static = "0.2.1"
rand = "0.3.14"
regex = "0.1.73"
serde = "0.8.1"
url = "1.2.0"

[dev-dependencies]
serde_json = "0.8.1"
