[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable types for the events in the Matrix specification."
documentation = "https://docs.rs/ruma-events"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.12.0"
edition = "2018"

[dependencies]
ruma-identifiers = "0.13.0"
ruma-signatures = "0.4.2"
serde_json = "1.0.39"

[dependencies.js_int]
version = "0.1.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.92"
features = ["derive"]
