[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings"]
description = "Resource identifiers for Matrix."
documentation = "https://docs.rs/ruma-identifiers"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.14.1"
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", optional = true }
rand = "0.7.3"
serde = "1.0.106"

[dev-dependencies]
serde_json = "1.0.51"
