[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Opaque identifiers for Matrix."
documentation = "http://ruma.github.io/ruma-identifiers/ruma_identifiers"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "matrix.org", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.1"
regex = "0.1.73"
url = "1.1.1"
