[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.1.0"

[dependencies]
futures = "0.1.21"
http = "0.1.5"
hyper = "0.12"
ruma-api = "0.5.0"
ruma-api-macros = "0.2.2"
ruma-events = "0.10.0"
ruma-identifiers = "0.11.0"
ruma-signatures = "0.4.0"
serde = "1.0.57"
serde_derive = "1.0.57"
serde_json = "1.0.17"
serde_urlencoded = "0.5.2"
url = "1.7.0"
