[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "An abstraction for Matrix API endpoints."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.5.0"

[dependencies]
futures = "0.1.15"
http = "0.1.0"
serde_json = "1.0.3"
serde_urlencoded = "0.5.1"

[dev-dependencies]
ruma-identifiers = "0.11"
serde = "1.0"
serde_derive = "1.0"
