[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.2.0"
edition = "2018"

[dependencies]
futures = "0.1.25"
http = "0.1.14"
hyper = "0.12.16"
ruma-api = "0.6.0"
ruma-api-macros = "0.3.0"
ruma-events = "0.11.0"
ruma-identifiers = "0.11.0"
ruma-signatures = "0.4.1"
serde_json = "1.0.38"
serde_urlencoded = "0.5.4"
url = "1.7.2"

[dependencies.serde]
version = "1.0.87"
features = ["derive"]
