[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable request and response types for the Matrix client API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.1.0"

[dependencies]
ruma-identifiers = "0.4.3"
serde = "0.8.19"
serde_derive = "0.8.19"
serde_json = "0.8.3"

[dependencies.ruma-events]
git = "https://github.com/ruma/ruma-events"
