[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "A procedural macro used by the ruma-events crate."
documentation = "https://docs.rs/ruma-events-macros"
edition = "2018"
homepage = "https://github.com/ruma/ruma-events-macros"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api-macros"
version = "0.1.0"

[dependencies]
syn = { version = "0.15.36", features = ["full"] }
quote = "0.6.12"
proc-macro2 = "0.4.30"

[lib]
proc-macro = true

[dev-dependencies]
ruma-identifiers = "0.13.1"
serde_json = "1.0.39"
js_int = "0.1.0"
serde = "1.0.92"
