[package]
name = "ruma-events"
version = "0.1.0"
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable types for the events in the Matrix specification."
license = "MIT"
readme = "README.md"
keywords = ["matrix", "matrix.org", "chat", "messaging", "ruma"]
repository = "https://github.com/ruma/ruma-events"
homepage = "https://github.com/ruma/ruma-events"
documentation = "http://ruma.github.io/ruma-events/ruma-events"
