[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "ruma-api-macros"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
synom = "0.11.3"

[dependencies.ruma-api]
git = "https://github.com/ruma/ruma-api"
rev = "4893be93f86543f9a9e3c5d7205afba769b84aa6"

[dependencies.syn]
features = ["full"]
version = "0.11.11"

[dev-dependencies]
futures = "0.1.14"
hyper = "0.11"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_urlencoded = "0.5.1"
url = "1.5.1"

[lib]
proc-macro = true
