[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "An abstraction for Matrix API endpoints."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.6.0"
edition = "2018"

[dependencies]
futures = "0.1.25"
http = "0.1.14"
hyper = "0.12.16"
serde_json = "1.0.33"
serde_urlencoded = "0.5.4"
ruma-identifiers = "0.11.0"

[dev-dependencies]
serde = "1.0.80"
serde_derive = "1.0.80"
url = "1.7.2"
