[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Digital signatures according to the Matrix specification."
documentation = "https://docs.rs/ruma-signatures"
homepage = "https://github.com/ruma/ruma-signatures"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-signatures"
readme = "README.md"
repository = "https://github.com/ruma/ruma-signatures"
version = "0.1.0"

[dependencies]
lazy_static = "0.2.1"
rustc-serialize = "0.3.19"
serde = "0.8.12"
serde_json = "0.8.2"
sodiumoxide = "0.0.12"

[lib]
doctest = false
