[package]
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix server-server API."
documentation = "https://docs.rs/ruma-federation-api"
edition = "2018"
homepage = "https://github.com/ruma/ruma-federation-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-federation-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-federation-api"
version = "0.1.0"

[dependencies]
js_int = "0.1.3"
ruma-events = "0.18.0"
ruma-identifiers = "0.14.1"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"
