[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A procedural macro for generating ruma-api Endpoints."
documentation = "https://docs.rs/ruma-api-macros"
homepage = "https://github.com/ruma/ruma-api-macros"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api-macros"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
ruma-api = "0.4.0"
synom = "0.11.3"

[dependencies.syn]
features = ["full"]
version = "0.11.11"

[dev-dependencies]
futures = "0.1.14"
hyper = "0.11"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"
serde_urlencoded = "0.5.1"
url = "1.5.1"

[lib]
proc-macro = true
