[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.3.0"
edition = "2018"

[dependencies]
futures = "0.1.27"
http = "0.1.17"
hyper = "0.12.29"
ruma-api = "0.8.0"
ruma-api-macros = "0.5.0"
ruma-events = "0.12.0"
ruma-identifiers = "0.13.0"
ruma-signatures = "0.4.2"
serde_json = "1.0.39"
serde_urlencoded = "0.5.5"
url_serde = "0.2.0"

[dependencies.js_int]
version = "0.1.0"
features = ["serde"]

[dependencies.serde]
version = "1.0.92"
features = ["derive"]

[dependencies.url]
version = "1.7.2"
features = ["serde"]
