[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
edition = "2018"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.2.0"

[dependencies]
futures-preview = "0.3.0-alpha.17"
http = "0.1.17"
ruma-api = { git = "https://github.com/ruma/ruma-api", branch = "endpoint_is_request" }
ruma-identifiers = "0.13.1"
serde_json = "1.0.39"
serde_urlencoded = "0.5.4"
url = "1.7.2"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"

[dependencies.hyper-tls]
optional = true
version = "0.3.2"

[dependencies.native-tls]
optional = true
version = "0.2.2"

[dependencies.ruma-client-api]
git = "https://github.com/ruma/ruma-client-api"
branch = "endpoint_is_request"

[dependencies.ruma-events]
git = "https://github.com/ruma/ruma-events"
rev = "1b0be0d0e7fa1040fc51b748256b290e24677b19"

[dependencies.serde]
version = "1.0.90"
features = ["derive"]

[dev-dependencies.tokio]
git = "https://github.com/tokio-rs/tokio"

[features]
default = []
tls = ["hyper-tls", "native-tls"]
