[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Core API types for Matrix."
documentation = "https://docs.rs/ruma-api"
homepage = "https://github.com/ruma/ruma-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api"
version = "0.1.0"

[dependencies]
serde = "0.8.21"

[dev-dependencies]
ruma-identifiers = "0.6.0"
serde_derive = "0.8.21"
