[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
name = "ruma-api-macros"
version = "0.1.0"

[dependencies]
quote = "0.3.15"
synom = "0.11.3"

[dependencies.hyper]
git = "https://github.com/hyperium/hyper"
rev = "fed04dfb58e19b408322d4e5ca7474871e848a35"

[dependencies.ruma-api]
path = "../ruma-api"

[dependencies.syn]
features = ["full"]
version = "0.11.11"

[lib]
doctest = false
proc-macro = true
