[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "A Matrix client library."
documentation = "https://docs.rs/ruma-client"
edition = "2018"
homepage = "https://github.com/ruma/ruma-client"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client"
version = "0.3.0-beta.1"

[dependencies]
futures-preview = "=0.3.0-alpha.19"
http = "0.1.19"
hyper = { version = "=0.13.0-alpha.4", features = ["unstable-stream"] }
hyper-tls = { version = "=0.4.0-alpha.4", optional = true }
ruma-api = "0.11.0"
ruma-client-api = "0.4.0"
ruma-events = "0.15.1"
ruma-identifiers = "0.14.0"
native-tls = { version = "0.2.3", optional = true }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0.41"
serde_urlencoded = "0.6.1"
url = "2.1.0"

[dev-dependencies]
tokio = "=0.2.0-alpha.6"

[features]
default = ["tls"]
tls = ["hyper-tls", "native-tls"]
