[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix client-server API."
documentation = "https://docs.rs/ruma-client-api"
homepage = "https://github.com/ruma/ruma-client-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-client-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-client-api"
version = "0.9.0"
edition = "2018"

[dependencies]
http = "0.2.1"
js_int = { version = "0.1.5", features = ["serde"] }
ruma-api = "0.16.1"
ruma-common = "0.1.3"
ruma-events = { git = "https://github.com/ruma/ruma-events", rev = "7395f94" }
ruma-identifiers = "0.16.2"
ruma-serde = "0.2.2"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
strum = { version = "0.18.0", features = ["derive"] }

[dev-dependencies]
maplit = "1.0.2"
matches = "0.1.8"
