[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings"]
description = "Serializable types for the events in the Matrix specification."
documentation = "https://docs.rs/ruma-events"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.18.0"
edition = "2018"

[dependencies]
js_int = { version = "0.1.4", features = ["serde"] }
ruma-identifiers = "0.15.1"
ruma-events-macros = { path = "ruma-events-macros", version = "=0.3.0" }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"

[dev-dependencies]
maplit = "1.0.2"
ruma-identifiers = { version = "0.15.1", features = ["rand"] }

[workspace]
members = [
    "ruma-events-macros",
]
