[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A procedural macro for generating ruma-api Endpoints."
documentation = "https://docs.rs/ruma-api-macros"
homepage = "https://github.com/ruma/ruma-api-macros"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api-macros"
version = "0.3.0"
edition = "2018"

[dependencies]
quote = "0.6.10"
ruma-api = "0.6.0"

[dependencies.syn]
version = "0.15.22"
features = ["full"]

[dependencies.proc-macro2]
version = "0.4.24"
features = ["nightly"]

[dev-dependencies]
futures = "0.1.25"
http = "0.1.14"
hyper = "0.12.16"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.33"
serde_urlencoded = "0.5.4"
url = "1.7.2"

[lib]
proc-macro = true
