[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
categories = ["api-bindings"]
description = "Resource identifiers for Matrix."
documentation = "https://docs.rs/ruma-identifiers"
homepage = "https://github.com/ruma/ruma-identifiers"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-identifiers"
readme = "README.md"
repository = "https://github.com/ruma/ruma-identifiers"
version = "0.14.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4.3", optional = true }
lazy_static = "1.4.0"
rand = "0.7.2"
regex = "1.3.1"
serde = "1.0.102"
url = "2.1.0"

[dev-dependencies]
serde_json = "1.0.41"
