[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Digital signatures according to the Matrix specification."
documentation = "https://docs.rs/ruma-signatures"
homepage = "https://github.com/ruma/ruma-signatures"
keywords = ["matrix", "chat", "messaging", "ruma", "cryptography"]
license = "MIT"
name = "ruma-signatures"
readme = "README.md"
repository = "https://github.com/ruma/ruma-signatures"
version = "0.4.0"

[dependencies]
base64 = "0.10.0"
lazy_static = "1.2.0"
ring = "0.13.5"
serde = "1.0.80"
serde_json = "1.0.33"
untrusted = "0.6.2"
url = "1.7.2"

[dev-dependencies]
serde_derive = "1.0.80"
