[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Serializable types for the events in the Matrix specification."
documentation = "http://ruma.github.io/ruma-common/ruma_events"
homepage = "https://github.com/ruma/ruma-events"
keywords = ["matrix", "matrix.org", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-events"
readme = "README.md"
repository = "https://github.com/ruma/ruma-events"
version = "0.1.0"

[dependencies]
serde = "0.7.10"
serde_macros = "0.7.10"
