[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "A procedural macro for generating ruma-api Endpoints."
documentation = "https://docs.rs/ruma-api-macros"
homepage = "https://github.com/ruma/ruma-api-macros"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-api-macros"
readme = "README.md"
repository = "https://github.com/ruma/ruma-api-macros"
version = "0.4.0"
edition = "2018"

[dependencies]
quote = "0.6.12"
ruma-api = "0.8.0"

[dependencies.syn]
version = "0.15.35"
features = ["full"]

[dependencies.proc-macro2]
version = "0.4.30"
features = ["nightly"]

[dev-dependencies]
futures = "0.1.27"
http = "0.1.17"
hyper = "0.12.29"
serde_json = "1.0.39"
serde_urlencoded = "0.5.5"
url = "1.7.2"

[dev-dependencies.serde]
version = "1.0.92"
features = ["derive"]

[lib]
proc-macro = true
