[package]
authors = ["Jimmy Cuadra <jimmy@jimmycuadra.com>"]
description = "Digital signatures according to the Matrix specification."
documentation = "https://docs.rs/ruma-signatures"
homepage = "https://github.com/ruma/ruma-signatures"
keywords = ["matrix", "chat", "messaging", "ruma", "cryptography"]
license = "MIT"
name = "ruma-signatures"
readme = "README.md"
repository = "https://github.com/ruma/ruma-signatures"
version = "0.2.1"

[dependencies]
ring = "0.6.3"
rustc-serialize = "0.3.22"
serde = "0.9.1"
serde_json = "0.9.1"
untrusted = "0.3.2"
url = "1.4.0"

[dev-dependencies]
serde_derive = "0.9.1"
