[package]
authors = ["Wim de With <wf@dewith.io>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix application service API."
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-appservice-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma"
version = "0.1.0"
edition = "2018"

[dependencies]
ruma-api = "0.16.1"
ruma-events = { git = "https://github.com/ruma/ruma-events", rev = "c1ee72d" }
ruma-identifiers = { version = "0.16.2", path = "../ruma-identifiers" }
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.52"
url = { version = "2.1.1", features = ["serde"] }
