[package]
authors = ["Wim de With <wf@dewith.io>"]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix application service API."
homepage = "https://github.com/ruma/ruma-appservice-api"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-appservice-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-appservice-api"
version = "0.1.0"
edition = "2018"

[dependencies]
ruma-api = "0.16.0"
ruma-events = "0.21.0"
ruma-identifiers = "0.16.1"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.52"
url = { version = "2.1.1", features = ["serde"] }
