[package]
authors = [
    "Jonas Platte <jplatte+git@posteo.de>",
    "Isaiah Inuwa <isaiah.inuwa@gmail.com>",
]
categories = ["api-bindings", "web-programming"]
description = "Types for the endpoints in the Matrix server-server API."
documentation = "https://docs.rs/ruma-federation-api"
edition = "2018"
homepage = "https://www.ruma.io/"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "MIT"
name = "ruma-federation-api"
readme = "README.md"
repository = "https://github.com/ruma/ruma-federation-api"
version = "0.0.2"

[dependencies]
js_int = "0.1.5"
matches = "0.1.8"
ruma-api = { version = "0.16.1", path = "../ruma-api" }
ruma-events = { git = "https://github.com/ruma/ruma-events", rev = "c1ee72d" }
ruma-identifiers = { version = "0.16.2", path = "../ruma-identifiers" }
ruma-serde = "0.2.2"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0.53"
